### ISSUE TITLE
proxy: does not handle modules using v2 directory convention

### ISSUE THREAD

**Issue by shoenig** [modprox/mp#122]
modprox does not correctly implement the `Major subdirectory` sub-section of the modules documentation:
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

This is preventing the import of things like 
`github.com/googleapis/gax-go/v2  v2.0.4`

```
$ go get github.com/googleapis/gax-go/v2
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: github.com/googleapis/gax-go/v2@v2.0.4: parsing go.mod: unexpected module path "github.com/googleapis/gax-go"
go: error loading module requirements
```

**Comment by billsmith** [comment]
I think this means modprox needs to append the version number to the module name if the major version is 2 or greater.

Will there need to be a change to the registry as well?
