### ISSUE TITLE
registry: setup continuous integration

### ISSUE THREAD

**Issue by johnstcn** [modprox/mp#15]
Travis CI is nice. https://travis-ci.org

**Comment by shoenig** [comment]
+1 I've never setup travisCI in the context of an organization, hopefully it all Just Works

**Comment by shoenig** [comment]
success! 
https://travis-ci.org/modprox/mp
@billsmith @johnstcn can you check to make sure you're able to login to travisCI and manage the modprox organization? 

the build is managed via the `.travis.yml` file in the root of the repository
```
$ cat .travis.yml 
language: go

go:
  - 1.11.x

install:
  - go get github.com/shoenig/petrify/...
  - go get github.com/shoenig/mockery

script:
  - go generate ./...
  - go build ./...
  - go vet ./...
  - go test ./...
```

**Comment by johnstcn** [comment]
@shoenig works for me. I'd already done the Travis CI setup previously though.
