### ISSUE TITLE
Incorrect import of minimock in go.mod file

### ISSUE THREAD

**Issue by shoenig** [modprox/mp#172]
Figure out where the incorrect import is coming from and get rid of it
```
[p1 modprox (master)] $ grep minimock go.mod
	github.com/gojuno/minimock v3.0.0 // indirect
	github.com/gojuno/minimock/v3 v3.0.1
```

**Comment by ovesh** [comment]
I can't reproduce this. What's the problem exactly?

**Comment by deadok22** [comment]
@ovesh `github.com/gojuno/minimock v3.0.0 ` is incorrect. The module name should be `github.com/gojuno/minimock/v3`.
