### ISSUE TITLE
proxy: seg fault 

### ISSUE THREAD

**Issue by billsmith** [modprox/mp#41]
`2018/09/11 09:52:43 INFO  [reload-worker] going to download https://github.com/golang/text/archive/v0.3.0.zip
2018/09/11 09:52:43 TRACE [zips-http] making a request to https://github.com/golang/text/archive/v0.3.0.zip
2018/09/11 09:52:44 INFO  [heartbeat-sender] sending a heartbeat: [bsmith-laptop:12505 1 2]
2018/09/11 09:52:44 INFO  [heartbeat-sender] send was successful
2018/09/11 09:52:46 INFO  [reload-worker] downloaded blob of size: 6267773
2018/09/11 09:52:47 INFO  [fs-store] will save (golang.org/x/text @ v0.3.0) do disk, 6349244 bytes
2018/09/11 09:52:47 TRACE [fs-store] writing module zip into path: /tmp/mod-zips/golang.org/x/text
2018/09/11 09:52:47 TRACE [reload-worker] downloaded (golang.org/x/text @ v0.3.0)!
2018/09/11 09:52:47 INFO  [go-get-transform] doing go-get redirect lookup for domain gopkg.in
2018/09/11 09:52:54 INFO  [heartbeat-sender] sending a heartbeat: [bsmith-laptop:12505 1 2]
2018/09/11 09:52:54 INFO  [heartbeat-sender] send was successful
2018/09/11 09:52:57 WARN  [go-get-transform] unable to lookup go get redirect to {  } (assuming none): no go-source meta tag in response
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x67d491]

goroutine 5 [running]:
github.com/modprox/mp/pkg/upstream.(*SetPathTransform).Modify(0xc00000cee0, 0xc000300310, 0xc000300310)
	/home/bsmith/go/src/github.com/modprox/mp/pkg/upstream/transformer.go:394 +0x61
github.com/modprox/mp/pkg/upstream.(*resolver).Resolve(0xc00000cf20, 0xc0002c6b00, 0x11, 0xc0002d8900, 0x22, 0xc00012a1a0, 0x460e8d, 0x12a1a0)
	/home/bsmith/go/src/github.com/modprox/mp/pkg/upstream/transformer.go:64 +0xb4
github.com/modprox/mp/proxy/internal/modules/background.(*reloadWorker).download(0xc000132080, 0xc0002c6b00, 0x11, 0xc0002d8900, 0x22, 0x3d, 0x0, 0x0)
	/home/bsmith/go/src/github.com/modprox/mp/proxy/internal/modules/background/worker.go:127 +0x80
github.com/modprox/mp/proxy/internal/modules/background.(*reloadWorker).acquireMods(0xc000132080, 0x759187, 0x14, 0x0, 0x0, 0x0)
	/home/bsmith/go/src/github.com/modprox/mp/proxy/internal/modules/background/worker.go:116 +0x602
github.com/modprox/mp/proxy/internal/modules/background.(*reloadWorker).loop(0xc000132080, 0x0, 0x0)
	/home/bsmith/go/src/github.com/modprox/mp/proxy/internal/modules/background/worker.go:69 +0x6c
github.com/modprox/mp/proxy/internal/modules/background.(*reloadWorker).Start.func1(0xc000198480, 0xc0000d5f98)
	/home/bsmith/go/src/github.com/modprox/mp/proxy/internal/modules/background/worker.go:57 +0x33
github.com/shoenig/toolkit.Interval(0x4a817c800, 0xc000061530, 0xc000012d01, 0xc000132080)
	/home/bsmith/go/pkg/mod/github.com/shoenig/toolkit@v1.0.0/interval.go:16 +0xa5
created by github.com/modprox/mp/proxy/internal/modules/background.(*reloadWorker).Start
	/home/bsmith/go/src/github.com/modprox/mp/proxy/internal/modules/background/worker.go:56 +0x77
`

**Comment by shoenig** [comment]
github is having a sad day
![githubdown](https://user-images.githubusercontent.com/394887/45369541-c68d8a80-b5ab-11e8-96d3-4ded03487e38.png)

... which is causing the go-get redirect transformer request to fail, which is causing a thing parsing the response to fail ....

We should be more defensive about the request transformations not working. When a module can't be downloaded right now, it will automatically be tried again and again in the future (as long as we don't crash).
